<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4cc684d8b68d9bad451b8468d2e4e748
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4cc684d8b68d9bad451b8468d2e4e748::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4cc684d8b68d9bad451b8468d2e4e748::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4cc684d8b68d9bad451b8468d2e4e748::$classMap;

        }, null, ClassLoader::class);
    }
}
